### ISSUE TITLE
Failed state: enforce the usage of these two models: idempotent operation or do&undo

### ISSUE THREAD

**Issue by zal-cwolters** [zalando/restful-api-guidelines#101]
**About managing the failed state.**

In our distributed micro service world:

whenever a data point is created or manipulated a subsequent operation (on a different service) may fail and therefore invalidates the initial creation or manipulation of data.

Depending on the action, there should be the possibility to undo a previous action to get back into a clean state and allow a retry of the whole action later.

E.g. by using rollback operations for all non-idempotent calls (e.g. POST -> DELETE) 

I would like to enforce the api guidelines so that there is always an idempotent operation in place or  a do&undo pair.

An often discussed pattern for this transactional problem is e.g. the _Saga Interaction Pattern_. See https://www.youtube.com/watch?v=xDuwrtwYHu8&ab_channel=GOTOConferences

**Comment by ePaul** [comment]
I'm not sure how `undo` fits into the REST paradigm with the HTTP methods.

A DELETE can only undo a POST if you managed to actually know the URL of the created resource – if you got an interrupted connection, you don't know whether the POST did succeed or not.
I also don't get while you want this just for non-idempotent methods ... you might want to undo a PUT too, right?

**Comment by whiskeysierra** [comment]
> I would like to enforce the api guidelines so that there is **always** an idempotent operation in place or a do&undo pair.

I see the use case for rollbacks in general and as an API provider I'll always consider adding endpoints/operations/resources for this, if it feels natural and if it semantically makes sense. I wouldn't go so far as to enforce this on everybody, because I don't think that it's always possible or that it always makes sense. E.g. you can't cancel a parcel delivery after a certain point. Nor can you *unsend* an email (I don't think that sending a second one is a good user experience in all cases).

Some other concerns:
- This effectively would require that every service keeps a complete version history so it can restore an older version **or**
- clients need to keep the complete old state in case they want to restore
- Event-based, asynchronous and loosely coupled communication makes this even harder, it would basically mean that we have compensating events for everything
- What about compensating compensations, i.e. can I cancel a cancellation?

**Comment by tfrauenstein** [comment]
Agreed -- it is out of scope of REST Guidelines. Distributed (logical) transactions may not be avoidable for specific use cases. It is a complex topic and there are different ways how to handle it -- I don't think we should standardise it, and not as part of REST guideline -- might be a topic for new microservice design practises paper.

**Comment by tkrop** [comment]
It might be covered by a separate micro service guideline we talked about, but than we would not be an API guideline guild any longer. But it seems as there is need for guidance here too.

**Comment by tfrauenstein** [comment]
Yes, I had this new paper in mind. And it is out of scope of current API Guild purpose, but in next Guild meeting we should discuss whether we want to extend the purpose or expect it to be delivered by architecture team.

**Comment by fmueller** [comment]
Will be discussed in some kind of Microservice patterns guidelines.
