### ISSUE TITLE
JSON vs. other media types as playload

### ISSUE THREAD

**Issue by tfrauenstein** [zalando/restful-api-guidelines#11]
In section https://github.com/zalando/restful-api-guidelines/blob/master/data-formats/DataFormats.md we have defined the following rule: "Must: Use JSON as the Body Payload"

I think this is not 100% correct. We already required compliance to OpenAPI standard. Here payload is defined compliant to JSON -- especially via Schema Object http://swagger.io/specification/#schemaObject. It is a subset of JSON scheme. We also want to support more general JSON scheme structures -- Sean planed a corresponding rule proposal. @mostlymagic Could you do a corresponding update of this rule? Thx.

**Comment by ePaul** [comment]
I don't really understand the issue here, can you explain a bit more?

OpenAPI defines a way of describing the API, but it actually allows both JSON and XML (if you use the right produces/consumes properties). Saying that we support just JSON is useful. Saying you should follow the JSON RFC (and not use some "variants" which might be out there, like different String delimiters, comments, ...) seems useful too, even if it might be thought to be implied.


The Payload/data model definitions in OpenAPI are a subset of JSON Schema (a subset which can be represented with classes in statically typed languages like Java). Do we really want to use a new extension of OpenAPI here to allow more definitions?

**Comment by mostlymagic** [comment]
I would personally suggest that we say APIs MUST support JSON but COULD support other formats (XML, PDF, CSV etc)

**Comment by fmueller** [comment]
+1 for @mostlymagic suggestion. Sure, there are use cases where you have to transfer binary data like PDF over the wire. For that, JSON as MUST and other formats as COULD sounds good.

**Comment by ePaul** [comment]
The discussion here is actually about two topics, which got mangled a bit.

Yesterday we decided to split them into two issues.
Here we want to handle the suggestion of "allow other media types than JSON". @fmueller will write a proposal of how to change the "use JSON" guideline in the data formats section.

For the point of "allow specifying object schemas in a different language than OpenAPI's one", we'll make a new issue.

**Comment by whiskeysierra** [comment]
> For the point of "allow specifying object schemas in a different language than OpenAPI's one", we'll make a new issue.

See #72
