### ISSUE TITLE
Include Pick Up Points in address object

### ISSUE THREAD

**Issue by pc-alves** [zalando/restful-api-guidelines#128]
For some delivery cases, addresses need to be enriched with some data that identifies a Pick Up Point. A location where the receiver can pick up his or her parcel. Think of packstations, and similar services in other countries.
I believe that this is a common enough use case to be included in the API guidelines. My suggestion is to have a separate optional object included in the address object.

**Comment by whiskeysierra** [comment]
> I believe that this is a common enough use case to be included in the API guidelines.

If you think in terms of *delivery address*, then yes. But not every address is for delivering something. We have e.g. billing addresses. But I see the point since eCommerce has a big emphasis on delivering stuff to the customer.

> My suggestion is to have a separate optional object included in the address object.

Which is pretty much what we have in one of our internal APIs. It looks like this:

```json
{
   "_links":{
      "delivery-product":{
         "href":"http://example.com/delivery-products/38"
      }
   },
   "destination":{
      "address":{
         "salutation":"Mr",
         "first_name":"John",
         "last_name":"Doe",
         "street":"Mollstr 1",
         "additional":"2nd floor",
         "zip":"10178",
         "city":"Berlin",
         "country_code":"DE"
      },
      "pickup_point_name":"Packstation 123",
      "pickup_point_id":"",
      "pickup_point_member_id":"123456"
   },
   "delivery_method":"parcel"
}
```

I strongly believe that this shouldn't make its way into our guidelines as the use case is too specific. Also our experience is only based on those carriers that we currently deal with. Comming up with something that is a) useful and b) flexible enough for the future is borderline impossible. Very similar to the whole concept of structured addresses, since they also don't work for everybody (Ireland has no zip codes, USA has apartment numbers, ...).

> Think of packstations, and similar services in other countries.

Actually, since you brought it up: Packstation in particular were introduced by DHL in a way that (obviously) wouldn't break the existing way everybody is handling addresses in Germany:

![image](https://cloud.githubusercontent.com/assets/429981/17928661/0ee6a06c-69fc-11e6-9bb8-c2960e9177ce.png)

Which means, based on this *specification*, you don't actually need any separate field. Also detecting/reading should be relatively easy (country_code = *DE* and street starts with *Packstation*).

**Comment by pc-alves** [comment]
I disagree that pick up points are too specific, but I understand why you wouldn't like to have it in the definition of the Address Fields. But it would make for a nice example of "_compatible extend it if necessary for your API concerns_". This is mostly where I was aiming at. That and raising the discussion.

I used Packstation as a mere example of a pick up point. And regarding the use of Street and Additional fields to hold the Packstation fields, I do not favor the reuse of fields in that way. Very easy to get it wrong (Is Packstation ID in the Additional, or Street?).

**Comment by whiskeysierra** [comment]
> I do not favor the reuse of fields in that way

The DHL which I'd consider the authority in that case defined it like that. It shouldn't be our decision to overrule that, not easily at least.

**Comment by pc-alves** [comment]
I feel we are going in the direction of Packstation input, instead of the topic of this issue. I used Packstation as a mere example of a Pick up point, and that was it.

Even my comment on the reuse of fields goes in the direction of having a separate object/field that clearly represents an extra property of an address. My argument for having it in the Guidelines is because I see it as a fairly common type of address (in the eCommerce industry, if nothing else). As you pointed out, it's hard to come up with a one-size-fits-all address and I agree. Hence my suggestion of having it as an example of extending the address object.

**Comment by ePaul** [comment]
Discussed in the API guild meeting:

The problem with pickup points is that every such service is different, and needs different information. Also, several kinds of addresses (like warehouse addresses, business partner addresses) don't need this information at all.

As such, we think it should not be defined in the basic address object given in the guideline – you can always extend the object in your API (as mentioned in the last sentence above the example).
