### ISSUE TITLE
UUIDs versus sequential (or speaking?) IDs

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#153]
* when to use what?
* configuration data (warehouses, sales channels, ...) vs. mass data (like articles, orders, ...)
* client vs. server side ID generation

**Comment by whiskeysierra** [comment]
**Pros**
- distributed id management becomes easier (but **not necessarily** [simpler](https://www.infoq.com/presentations/Simple-Made-Easy))

**Cons**
- poor readability for developers (log files, etc.) and  readability/usability for end users (in case they are exposed as e.g. invoice numbers)
- length of 36 characters (by default) can at most be reduced to 23 characeters (`uuid -F BIN | base64 | sed 's/=//g'` produces `6FVxOKZhEeaFzKOd3UAmeg`)

**Comment by ePaul** [comment]
The main reason to use an UUID as an identifier for entities is to make sure no one else generates the same ID for a different entity (whether of same or different type).
This is reached by having a vast space of possible values, and using either good (pseudo)randomness or some namespace mechanism (time + MAC address + counter) to select values from that space.

This vast space makes the UUIDs long (128 bits → 16 bytes, 32 in hexadecimal (with standard delimiters 36), 22 chars in base64)). This is not really a problem when storing or transmitting them (storage and bandwith is cheap and becoming even cheaper), but it is when reading them, in logs, for phone calls etc.

For configuration data like business partners, warehouses, sales channels, etc. creations are not that often that we need to ensure concurrent creations – a simple counter would be enough, or possibly a speaking identifier ("code") selected by a human user (like as we are using for warehouses in Wholesale context: `WH-DE-EF` for our Erfurt warehouse, `WH-IT-ST` for the one in Stradella).
When different business organizations are creating the same type of entity, possibly namespace prefixes as discussed in #62 are a solution – while here the combined identifiers might get even longer than UUIDs, they still are much more easily to read, type and compare for humans.

**Comment by tlossen** [comment]
i think that UUID's should only be used if ID's have to be generated in a distributed (= uncoordinated) manner by multiple actors. basically, what they were invented for. in all other cases, costs (lack of readability, index-friendlyness etc.) outweigh their benefits.

or, as [richard clayton](https://rclayton.silvrback.com/do-you-really-need-a-uuid-guid) puts it:
> UUID's should be a last resort tactic,employed only after you have exhausted other strategies for determining uniqueness in an architecture.

**Comment by fmueller** [comment]
As discussed in todays guild meetup we wanna form a rule out of this and place it in resources chapter.

@tlossen is in the lead

**Comment by chridou** [comment]
UUIDs and sequential ids/numbers share an important property. They are fixed sized data types. Strings are dynamically sized and can therefore only live on the heap. This forces the CPU to do pointer chasing. 

So basically an id should fixed sized. But for strings this might be quite hard to enforce(fixed number of chars and only ASCII).

But there is just more to it than the explanations given in the guidelines. Especially when requests are processed with a high frequency Strings can cause trouble.

**Comment by hjacobs** [comment]
@chridou that sounds like premature optimization, I don't think we want to optimize APIs for fixed width data types --- most of our Zalando services run on the JVM, so there is already "some" overhead. On the other hand I agree that some fixed-width "format" for the ID (application dependent) makes sense, AWS resource IDs are a good example (they all have a prefix indicating the resource type, e.g. `i-34fcc185` indicates an EC2 instance ID and `sg-23fd12c` would be a Security Group).

**Comment by chridou** [comment]
@hjacobs I agree that it sounds like that. On JVM it currently doesn't matter, but I heard that with Java 9 structs are planned. I think for the guidelines it is also important to point out that strings have their drawbacks and should also only be a last resort on the other side of the end: Use strings only if there is a strong need for them. So I would add something like "If ever possible choose a sequential number as the Id" because that is somehow something that combines (best and almost worse) of both worlds.


Not really contributing to this discussion but interesting:
Maybe this talk from Facebook is interesting showing how much effort they spend on the topic, especially how much time they spend in "Strings" CPU wise.
 
https://www.youtube.com/watch?v=kPR8h4-qZdk

**Comment by hjacobs** [comment]
@chridou probably you should go with GRPC instead of trying to micro-optimize JSON REST APIs :smirk:

**Comment by dehora** [comment]
@chridou I'd suggest coming at this from a different angle and having a recommendation that id strings across the APIs have a maximum char length, perhaps with some wording to consider, but not require, uniform length. That allows APIs and their implementations to negotiate efficiencies like fixed-width, which might be important for some real-world scenarios (making them 64 bit to keep them cache lined, etc) but doesn't impose on other API implementations. I know some folks won't like the idea of saying API ids will always fit inside a varchar(96) or what have you, but they practically speaking have to be stored somehow and shouldn't force developers away from systems efficiencies.

I also think we need to discourage format qualification of id strings (such as `uuid`) even where the ids happen to be lexically of that type on the wire. That kind of type narrowing makes long term API evolution over time harder because code (and downstream API definitions) end up locking into the type declaration. The way the APIs are at the moment, an API designer has no idea how their ids will be distributed and used, making it basically impossible to change format without risking a break.

 / @hjacobs @tlossen

**Comment by chridou** [comment]
@hjacobs 

> probably you should go with GRPC instead of trying to micro-optimize JSON REST APIs :smirk:

Good to know there are G and other companies out there that choose optimization in favour of eternal mature latency ;-)

**Comment by fmueller** [comment]
I close this, @tlossen, as we already merged your PR for this.
