### ISSUE TITLE
Does the rule Avoid JavaScript Keywords make sense?

### ISSUE THREAD

**Issue by fmueller** [zalando/restful-api-guidelines#167]
What was the reasoning behind the rule [Reserved JavaScript keywords should be avoided](http://zalando.github.io/restful-api-guidelines/json-guidelines/JsonGuidelines.html#should-reserved-javascript-keywords-should-be-avoided) in our API guidelines?

@dehora Can you follow up with more explanation regarding *security and sanity reasons*?

**Comment by dehora** [comment]
> Can you follow up with more explanation regarding security and sanity reasons?

The sanity thing is around avoiding issues with dotted vs string notation for object properties that happen to be keywords,  Google's JSON guidelines mention dot notation for example as a reason to avoid javascript keywords. Otherwise it was to be paranoid about lifting json into executable javascript Not having javascript keywords in the data mitigates this. Now, it's possible this is simply not a threat and the guidelines are overly cautious, but we'd want to be fairly sure ("I don't see the threat" isn't exactly a compelling security mindset).

**Comment by hjacobs** [comment]
IMHO we should remove that guideline, I think in fact nobody actually follows it (or do you know anybody reviewing an API seeing the "class" property to mark it?).

There are some valid names for properties which are JavaScript keywords which I would rather like to use without thinking about alternatives, e.g.:

* `class`
* `default`
* `function`

**Comment by tfrauenstein** [comment]
👍  let's remove it -- not primarily because API usage of these keywords so important, but...
* rule is vague -- avoid keywords in everywhere in json, i.e. in name and value strings?
* security threat is very vague -- how should specific API payload defined by specific API owner be lifted into executable code, and by whom?

AFAIK our components don't lift json into executable javascript. And if one would do it, a couple different of security risk mitigation actions have to take place inside this component, but not in advance by the rest of the world. 
So, I don't see a more concrete security threat and the rule feels too vague and a bit paranoid.
