### ISSUE TITLE
Mention validation logic as part of API and therefore considerable for possible breaking changes

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#177]
What happened? One team changed validation logic because it was too strict. This caused issues in writing api client user of their service. Discussion in the API guild today made clear that it was mostly missing communication between the teams.

It's an open discussion topic if we should mention in our guidelines that validations are also part of the API and should not break in a non-backward compatible way.

**Comment by MariaDodevska** [comment]
As we all find out the biggest challenge that came with the new microservive architecture is communication. 
1) I think we should first follow the "Rules of play", but sometimes that is not enough. 

2) Ideally the process of communicating API changes would be automated. Maybe PACT Testing is a solution, but maintaining them will be pretty time consuming. We can discuss on the topic and try to come up with something. 

3) The easiest solution for time being I think would be to send an email to inform the consumers of our API about the changes that are due to happen. We can work together on creating a template for such email. Also, we should try to find a way to define when these email should be send (e.g: when the API becomes more restrictive than before or when it can break backwards compatibility). Doesn't make sense to send email for each PR.

**Comment by fmueller** [comment]
@MariaDodevska I added notes from our guild meeting today.

Breaking API changes are simply not allowed by our API guidelines. If they are necessary, you have to negotiate with all your clients how to make this possible (if your API is only internal and you know all of them) or introduce versioning.

I don't think that automatic mailing notifications are the way to go here as this should not happen and for the rare case it does, we have rules to solve this. Having such an automatic mailing list is a technical solution to a people problem. And especially in this case, the team knew it had to communicate this change to its clients - it just forgot it.

**Comment by dehora** [comment]
@MariaDodevska @ePaul @fmueller can you be specific about what a "validation logic"  change is in this case?

**Comment by fmueller** [comment]
It was about naming of DHL packetstations.

**Comment by tfrauenstein** [comment]
Of course, strengthening service side validation logic is an incompatible interface change. 
As we had some recent live outages with such issues, some additional hints and a guideline about "API management" could be helpful. Let's draft a PR.

**Comment by ePaul** [comment]
Important: useful error messages for business rules violations, and describe their format in the API.

**Comment by tkrop** [comment]
@tfrauenstein Can you although solve this with #248?

**Comment by ePaul** [comment]
Was fixed by #248.
