### ISSUE TITLE
Clarify client-side requirements around X- headers

### ISSUE THREAD

**Issue by dehora** [zalando/restful-api-guidelines#228]
The [Proprietary Headers](http://zalando.github.io/restful-api-guidelines/headers/ProprietaryHeaders.html) indicate API use of well-known X- Headers is optional:

>  Whether services support these concerns or not is optional

X- headers (ignoring the history of the X- prefix for experimental development) are often discretionary for clients (eg MSFT's guidelines state they should not be required for an API to work).

As an example, last March, the Nakadi API, which is based on these guidelines was asked to remove the use of X- header:

> headers should be reserved for contextual information like language or flow-ids that are not part of the data / data model of the API.

That was in the context of querying, the full discussion is [here](https://github.com/zalando/nakadi/pull/593#discussion_r106128860). That guidance is reasonable but more generally whether API designers can demand clients must use X- headers  to work effectively with a service should be clarified.

**Comment by ePaul** [comment]
(We didn't get to this in today's meeting, might discuss it next week. Here are my personal comments.)

I think this is not specific to `X-`-headers, but header parameters in general. I think (and that was also my input to that discussion – which then resulted in #217) that header parameters should not be used as a main input for any API, but just as context information:

> From a conceptual point of view, the semantic of an operation should always be expressed by resource name and query parameters, i.e. what goes into the URL. Request headers are reserved for general context information, e.g. FlowIDs.

Some of those headers could be required (like Authorization, Content-Type ... though those are not explicitly in the API), while others would be optional. I don't think handling X-headers differently than standard headers is needed here.

Do we need to make that rule more visible?

**Comment by dehora** [comment]
> Do we need to make that rule more visible?

Yes. But to stay on topic, X- headers need special consideration. As one example an API that can't function without them being sent, is much harder to externalise, which goes against the wishes of the guidelines and Zalando's own top level principles that aren't part of these guidelines but do inform them. As another example, the tenancy headers will impact caching because any cacheable result now needs to use vary instead of relying on the distinct URL (the reality in that case is intermediary caching won't be an deployed option). In turn that complicates client and server operations because request logs carry less meaning. And it breaks resource identification or causes unorthodox API design relying on trusting clients to create unique resources (see elsewhere for issues around using UUIDs as identifiers) And so on. These headers have room for significant impact when required to used by clients.

Some "regular" headers are controls and do affect the outcome (cache controls, authorization, content negotiation, etc). I'm not so much concerned about those, as the non-uniformity of adding X- headers.

**Comment by ePaul** [comment]
**From the meeting**: We are looking through the headers listed there:

* X-Flow-ID: is needed for tracing. We should add some guidelines about how they should be provided/handled. → new issue.
* X-UID – seems superfluous. Currently used mostly in legacy services. → create new issue.

For these we are not sure:

* X-App-Domain (replaced by sales channel)
* X-Sales-Channel – this and app-domain determine a lot of order flow details. The reason for being headers is historical. Maybe we could remove them from the guidelines?

The following headers are meant to be passed through to called services, in case a service deep down in the call hierarchy needs access to some of the information (like recommendation):

* X-Frontend-Type
* X-Device-Type
* X-Device-OS
* X-Tenant-ID – currently needed for multi-tenant platform-internal services. We don't want to touch this now.

We should add some guideline about the pass-through behavior.

In general, our APIs do not support transparent HTTP caching (because they are authenticated).
We should add a rule for this → new issue.

**Comment by duergner** [comment]
**From the meeting:** In addition to the points mentioned above the guidelines should be adopted to give the following guidance.

Zalando proprietary headers like e.g. *X-Flow-ID* or *X-Device-Type* need to be passed on downstream from service to service without change.

RFC defined X headers like e.g. the rate limiting ones can be used on API definitions whenever they make sense.

Beside that the guidelines should discourage usage of X headers.

The guideline change will include reasoning for the decisions.

**Comment by maxim-tschumak** [comment]
@duergner 
> RFC defined X headers like e.g. the rate limiting ones can be used on API definitions whenever they make sense.

There are no RFC defined X headers anymore, they are deprecated by IETF ([RFC-6648](https://tools.ietf.org/html/rfc6648))
I' going to use `conventional X headers` wording in the guideline.

**Comment by maxim-tschumak** [comment]
Related issues have been created, I'm preparing the PR for the guideline changes.
