### ISSUE TITLE
Add guidance on large numbers in JSON and interoperability

### ISSUE THREAD

**Issue by dehora** [zalando/restful-api-guidelines#235]
JSON the specification doesn't provide a limit on the number production in its grammar but very long numbers or doubles with a long mantissa may lose precision when processed by common implementations (such as JavaScript). 

[rfc7159](https://tools.ietf.org/html/rfc7159) allow arbitrary long number productions in its grammar but says implementations may impose limitations without saying what they are. This tends to result in interoperability problems and disagreements on who's responsible for the issue.

**Comment by SergKam** [comment]
Link to a real life issue 
https://techjira.zalando.net/browse/ARUHA-804

**Comment by whiskeysierra** [comment]
> Link to a real life issue
> https://techjira.zalando.net/browse/ARUHA-804

Since it's internal it's not very helpful for externals. It basically describes the case that a number was used to represent an ID. The trivial fix should've been to use a string here. Numbers should only be used for numeric values. I feel like this is the actual rule that we need to emphasize here.

**Comment by dehora** [comment]
> It basically describes the case that a number was used to represent an ID. The trivial fix should've been to use a string here. Numbers should only be used for numeric values. I feel like this is the actual rule that we need to emphasize.

There is guidance elsewhere on using strings for ids, think this is more general to do with numbers in JSON. wrt to the internal ticket If the field was not an id, the same interop problem would have arose where two teams are pointing at each other for a fix.

**Comment by valgog** [comment]
This topic was already discussed several times, but the only mentioning of the problem (as far as I know) is related to Money object: https://github.com/zalando/restful-api-guidelines/blob/master/common-data-objects/CommonDataObjects.md

Parsing numbers out of JSON is a big problem in most of the existing libraries (especially in typed languages). We need a separate section, that describes not only the problem, but also provides some hints on best practices and known bugs in the most common JSON parsers (including Node)

**Comment by valgog** [comment]
@dehora I think the responsibility issue is clear, it is the responsibility of the client to parse correctly. This was a though when we standardised Money object.

Changing it according to reality of the situation with limited implementations, prohibiting usage of `number` in JSON will push the responsibility of the data producers.

**Comment by dehora** [comment]
> I think the responsibility issue is clear, it is the responsibility of the client to parse correctly. 

Right, but technically not so since rfc7159, which is why the guidance is needed. From "[6. Numbers](https://tools.ietf.org/html/rfc7159#section-6)":

> This specification allows implementations to set limits on the range  and precision of numbers accepted. 

Clients don't have to honour precision, so the problem is baked into the most recent RFC (that wording didn't exist in rfc4627).

**Comment by zrobgar** [comment]
Guidance is neccessary, Expeccially in regards to internal issues. The numbers that we are considering here are an ID, this is not a number, nor can it be considered nor treated as a number. It is and should be considered to be a text field, unless someone, somewhere, somehow thinks we are going to start multiplying order ids by each other, or otherwise doing arthimetic on them, they are just an identifier and should be treated as such.

**Comment by SergKam** [comment]
I found some good rule in our guidelines addressing this.
http://zalando.github.io/restful-api-guidelines/resources/Resources.html

> Should: Only Use UUIDs If Necessary
>... In any case, we should always use string rather than number type for identifiers.
Can we just separate this mention in its own rule?

**Comment by ePaul** [comment]
I think we have two issues:

**IDs should be strings, not numbers**. I guess we all agree here?

For numbers (both `type: number` and `type: integer`), JSON does not prescribe any size/precision limit (but tells that implementations can put limits), and OpenAPI doesn't either (if no format is given).
I'm not sure where we use non-integer numbers other than for money values (which is covered by the Money guideline).

And do we ever handle (non-ID) integers which are bigger than what i.e. 32 bit can cover? (Maybe the number of items sold in a whole year, or similar, will reach this soon.)

The problem with using IEE 754 is that it is for binary fractions, while the (non-integer) numbers we are transmitting are decimal ones. While all binary fractions can be represented as decimal ones (with the same number of digits), the converse is not true (if you have a decimal number, then converting it into a binary one might give an infinite fraction, or loose precision).

Instead of limiting the number format in our guidelines by prescribing a specific format, maybe we should specify that API designers have to define a format whenever using `number` (or `integer`)?
OpenAPI offers `float` and `double` for people who want IEE 754, and we already introduced `decimal` for our money object, which can be used in general for arbitrary-precision *decimal* numbers.
For integers, there is `int32` and `int64`, do we need something for "arbitrarily large"?

**Comment by dehora** [comment]
> I found some good rule in our guidelines addressing this.
> http://zalando.github.io/restful-api-guidelines/resources/Resources.html
>
>> Should: Only Use UUIDs If Necessary
>> ... In any case, we should always use string rather than number type for identifiers.
>
>Can we just separate this mention in its own rule? 

@SergKam if you want to discuss IDs specifically, please open another issue. This issue is for guidance around numbers generally.

**Comment by dehora** [comment]
> I think we have two issues:
> 
> IDs should be strings, not numbers. I guess we all agree here?
> 

@ePaul As I've pointed out twice already, IDs are a different, specific subject.

**Comment by tkrop** [comment]
1. Our `string` rule for `id` is very implicit (http://zalando.github.io/restful-api-guidelines/common-data-objects/CommonDataObjects.html#must-use-common-field-names). It's hard to deduce from it, that every id should be represented as `string`. We should have a top level rule for any field containing a reference/id to an entity to prevent this kind of problem. If some one still expects a certain format for the ID, he might add a pattern to declare that only numbers of a certain length are allowed.

2. The large number issue should be addressed by adding a format as suggested by @ePaul. In addition, we may add the rule that all clients have to take care to support arbitrary sized numbers by default for compatibility, if no format is provided.

**Comment by ePaul** [comment]
**Discussed in the meeting**:

* Whenever a `number` or `integer` is used, a `format` needs to be there, too.
* We use the formats `float`, `double` (standard OpenAPI) and `decimal` (for arbitrary-precision *decimal* numbers) for `number` – the latter is preferred for money-related stuff.
* We use the formats `int32`, `int64` (standard OpenAPI) and `bigint` (for arbitrary-size integer numbers) for `integer`

**Comment by ePaul** [comment]
**From the meeting**:  
About the `id` as string or integer: We agree that the sentence at the common field names rule is too hidden. We don't really agree whether it should be more visible (a separate rule) or not be there at all.
