### ISSUE TITLE
Highlighting of sort key(s) in data change events

### ISSUE THREAD

**Issue by SebastianNelk** [zalando/restful-api-guidelines#245]
The actual event schema definition does not explicitly state the sort key of data change events.

Please create a guideline to highlight the sort key in the event schema definition taking into concern that this could be distributed across multiple properties.

This is important to enable consumers to ensure the right event order during consumption.

Thanks!

**Comment by ePaul** [comment]
This is related to rule [203](http://zalando.github.io/restful-api-guidelines/#203). I guess this rule should adapted here to say how to indicate the ordering key in the event schema definition.

**Comment by codekultur** [comment]
We already have a field named "parent_eids" in the event metadata section, which can be used for partial and absolute ordering (depending on the interpretation of the sender). IMHO it makes sense to use this field for ordering. Maybe we just need to extend the metadata by a specification if the order defined via this parent id, is either a partial or absolute order.

What do you think?

**Comment by SebastianNelk** [comment]
Following the guildlines:
http://zalando.github.io/restful-api-guidelines/index.html#198

This is what parent_eids is ment for:
    parent_eids:
      description: |
        Event identifiers of the Event that caused the generation of
        this Event. Set by the producer.
      type: array
      items:
        type: string
        format: uuid
      example: '105a76d8-db49-4144-ace7-e683e8f4ba46'

So using it as order filed doesn't match for my understanding. Metadata should be extended by something like:
    order_attributes:
      description: |
        List of attributes to be used for ordering in event consumption. Set by the producer.
      type: array
      readOnly: true
      items:
        type: string
       example: ["cSKU", "timestamp"]

**Comment by codekultur** [comment]
Well, it depends on what "Event identifiers of the Event that caused the generation of
this Event." means or how it is interpreted. I would read it as the event that is the predecessor of the event in question, which IMHO defines an order.

Or is the parent_eids field used for something else and I misinterpreted the description (maybe we should then think about sharpening the description).

**Comment by SebastianNelk** [comment]
It's clearly highlighting it have to be eids like in business event of "order placed" created afterwards "billing provider contacted". What we are looking for is a order of consumption of the actual event it is defined for.

**Comment by ePaul** [comment]
If the eid is an UUID created by one of the usual processes, ordering by it does not work (because creation time is not conserved). If the eid is a counter just formatted in UUID format, we can order by it.

The `parent_eids` field works for grouping events which are related to each other (like the example given by Sebastian), but not so much for ordering unrelated events for the same entity.

**Comment by codekultur** [comment]
Of course you cannot order by the parent id. What I mean is: With help of the `parent_eids` you can build a chain of events (think of a linked list). This is a often used pattern to bring order to events in a distributed system.

E.g. Event id 23 is a "order #999 placed" event. Event id 42 (e.g. "order #999 shipped")  has  event id 23 as parent. Event id 84 (e.g. "invoice of order #999 payed") would have event id 42 as parent.

This way you can build a ordered history of what happened to one order. And you can - in contrast to a field by which you order (order by...) - detect if you missed some events in the middle.

The field `parent_eids` is a array, because in a system, where multiple senders (that are not synchronized) can create events referring to the same entity, one event can have multiple predecessors. (which we might not have in many cases)

@SebastianNelk I like to understand better what you are planing to do - I will contact you through another channel...

**Comment by SebastianNelk** [comment]
Looking forward for our Hangout, but to give you a heads-up I want to ensure that the changes of entities which are delivered via data change events are consumed in the right order and also compaction is working correctly. For that a ordering of the events per entity is required which can't be ensured by clocks in distributed systems or any other information actually available in the event schema.

**Comment by ePaul** [comment]
I think we are looking at different things here.

For (business) events of (potentially) different event types, which somehow belong together, and are caused by the previous event, `parent_eid` is the way to go. (E.g. the events for the sales order processing steps.)

For events about changes in the same data entity (i.e. data change events), caused by different (unrelated) triggers, this will not work, and we need some ordering key given by the sender, and usable by the consumer of the events (as already indicated in the guidelines).

**Comment by codekultur** [comment]
@ePaul I wouldn't say that you cannot use parent_eid for ordering data change events: You could introduce a version-id in your entity and use this version-id as the event_id and refer to the previous version of the same entity with help of the parent_eid. This way you could not only order events referring to the same entity, but also detect missing events (because the sender creates a linked list of all events). This is basically the idea of vector clocks...

**Comment by codekultur** [comment]
All in all I would say that using the parent_eid (vector clock) approach is the most generic one to introduce ordering AND detecting missing events.

There are two types of consumers: The ones interested in the whole history of one entity (e.g. "what happened to order 42?") and the systems only interested in the most current state of an entity (like currently the BI systems). With the parent_eid approach we have a generic approach to satisfy the needs of both types of clients.

But: For clients only interested in the most current version of a entity, the parent_eid approach is a bit heavy weight. Those systems would need to keep multiple versions of an entity to re-build the liked list to find out the event representing the newest version of the entity. This is why I would vote for a hybrid approach:
- We introduce a version number for all those entities. This version number is strictly monotonic increasing: Whenever a entity is changed, the version number is increased.
- The version number is used as event id and the previous version number is set in the parent_eid field.
If the version number is strictly monotonic increasing, clients only interested in the latest version of an entity could just look at the event-id and see if the version is higher or lower than the version they currently have.

If we don't want to use the event-id for the version information, we could rename the parent_eid field to parent_version and keep version information independent of the event id. If we do so, we would need a way to declare the version field somewhere in the event definition, so that consumers know which attribute represents the version they should look at.

BTW: If we want to enable multiple services making changes to the same entity, the parent_eid field should be an array (like common in vector clocks).

What do you think?

**Comment by whiskeysierra** [comment]
I always understood parent id as the event that caused this event and not
the previous data change event. Is there some formal specification?

**Comment by codekultur** [comment]
I don't know of any formal description. The field is interpreted (and used) in both ways, as far as I know. Maybe we need both: A parent_eid field (liked used in vector clocks) and a causing_eid field (that identifies the causing event).
@whiskeysierra Do you have good examples, where the causing event is needed?

**Comment by SebastianNelk** [comment]
@codekultur I'm sorry to disappoint you but by that approach you are not fulfilling the BI needs, as you would force us to consume every single event so would no longer be able to compact event streams to only get the latest version of an entitiy.

**Comment by codekultur** [comment]
@SebastianNelk No, you would not need to store every event if the version-number is strictly monotonic increasing: You just need to take a look into the version number to see if the version carried in the event is older or newer than the version you currently have. In any case you'll have to consume every event (otherwise you won't be able to have the latest version for your compaction).

As I understood, BI systems are only interested in the most current version. With just comparing the monotonic increasing version numbers you can easily detect the most current version. But having the parent_eid linked list of events, too, systems interested in the complete history of an entity can detect gaps.

**Comment by SebastianNelk** [comment]
@codekultur eids are uuids and not all teams are generating them as strictly monotonic ascending counter so when going for paretn_eid, we would be forst to build the whole list.
Having a version filed which is highlighted as such which is maintained by strictly monotonic ascending counter we would be more than happy.

**Comment by ePaul** [comment]
*From the discussion in the meeting*:
- one or more (array?)
  → ask Sebastian
- JsonPath → JsonPointer
- ask Nakadi on implementability

**Comment by SebastianNelk** [comment]
As discussed with ePaul, I reached out to the Team providing our tooling and we would currently not be able to use multiple fields for sorting, but a valid example to use this would be a data change event of which I want to consume just the latest state of the included business entity by ordering for minor - and major version like 1.1 < 1.2 < 2.1

**Comment by tkrop** [comment]
Finished! :+1:
