### ISSUE TITLE
X-Flow-ID Guidelines

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/restful-api-guidelines#251]
The new guideline(s) should include:
- How to handle `X-Flow-ID`
- What are the boundaries (scope) of the `X-Flow-ID`
- Which properties should apply to `X-Flow-ID`
- When to generate a `X-Flow-ID` and how should it look like
- Further explanations and reasoning

Related to / triggered by #228.

**Comment by ePaul** [comment]
**From the meeting**: Maybe we can copy some text from the tracer library.

**Comment by tkrop** [comment]
Is only explicitly defined in 103 of 250 apis.

**Comment by ePaul** [comment]
**From the meeting**:

* We want to have a guideline about distributed tracing
* The flow-ID should be passed through events, too
* Should API definitions include the definition of the header?

@whiskeysierra will collect ideas from @tkrop and @tfrauenstein, possibly also from @valgog and @dehora, and write it together.

**Comment by whiskeysierra** [comment]
I wrote my understanding of the current situation in a document and shared it with the guild + people mentioned above. This should be a starting point for the upcoming discussions.

**Comment by tkrop** [comment]
From guild meeting: make contact with tracebility initiative.

**Comment by akauppi** [comment]
@whiskeysierra Would like to have access to the doc you mentioned.

**Comment by ePaul** [comment]
We might replace this with OpenTracing, which is currently being discussed. On hold for now.

**Comment by ePaul** [comment]
We want to invite some experts from SRE team, and see whether the OpenTracing rollout will fulfill the needs we have with FlowID.

**Comment by gewald** [comment]
Can we discuss this issue in next API-Guild meeting how to get this done? For me it's not really clear how many changes should be done. Questions from my side are:
- When the issue was created, @maxim-tschumak (Jun 22, 2017) had some hints about what guidelines should include like "How to handle `X-Flow-ID`", "What are the boundaries (scope) of the` X-Flow-ID`", etc... Is this still valid and should this be still considered?
- There is also another comment from @ePaul (Sep 26, 2017) about new agreed requirements which are "We want to have a guideline about distributed tracing", "The`flow-ID` should be passed through events, too" and "Should API definitions include the definition of the header"? I think a guideline about distributed tracing should be done by [OpenTracing WorkingGroup](https://github.bus.zalan.do/SRE/opentracing). So there should be at least a link in the API-Guidelines to the guidelines or best practices of OpenTracing as further explanation. "Should API definitions include the definition of the header" might makes sense to introduce it in API-Guidelines.
- Should we restructure topic [Must: Use Only the Specified Proprietary Zalando Headers [183]](https://opensource.zalando.com/restful-api-guidelines/#183) at least section `X-Flow-ID`? I have the feeling that the existing description of `X-Flow-ID` gets messy if we add more information.

**Comment by gewald** [comment]
Meeting from 4th Dec 2018:
- Creating a new rule and reference it from X-Header explanation table
- X-Flow-ID rule is MUST
- Attach flow-id to OpenTracing span 
- Generate flow-id randomly unique 
- It's recommended that API-Clients provide a flow-id
