### ISSUE TITLE
Version number usage breaks GET-what-you-PUT guideline

### ISSUE THREAD

**Issue by ddufourboivin-zalando** [zalando/restful-api-guidelines#407]
In [this section](https://opensource.zalando.com/restful-api-guidelines/#_version_numbers).

```
< GET /orders

> HTTP/1.1 200 OK
> [
>   { code: "O0000042", version: 1, ... },
>   { code: "O0000043", version: 42, ... }
> ]

< PUT /orders/O0000042
< { code: "O0000042", version: 1, ... }
```

I submit to you that this is wrong.

The `PUT` is then not idempotent, since the next `GET` will return the resource with a `version: 2` instead of `version: 1`. The `PUT` operation is then no longer idempotent.

To respect that rule, the `PUT` should be made with the `version` property already incremented. The server then checks if that `version` is the same or lower than the actual server-side value and decides on when there is a conflict or not.

**Comment by dehora** [comment]
> I submit to you that this is wrong. 

PUT can't be wrong at the uniform interface level because it means "replace" and the request is asking the resource owner to replace the resource state at that URI with the request entity in the PUT. What is expected to happen, assuming no other agent is also manipulating the resource state, is that a subsequent GET returns the replacement `{ code: "O0000042", version: 1, ... }`

> The PUT is then not idempotent, since the next GET will return the resource with a version: 2 instead of version: 1. The PUT operation is then no longer idempotent.

So, being wrong here depends on what the example is trying to achieve and I'd suggest the guild think through the intent. At the interface level what's in the guidelines is ok, but probably not what's intended - PUT doesn't care what the meaning of `version` is.

PUT is imo hugely overrated for application semantics, people seem to endlessly confuse replace with create and update, and this is a great example of that, but that's another discussion.

**Comment by whiskeysierra** [comment]
> The PUT is then not idempotent, since the next GET will return the resource with a version: 2 instead of version: 1. The PUT operation is then no longer idempotent.

> If that's important to the resource owner, then perhaps the example should return a conflict, but strictly speaking, this isn't an idempotence problem.

I believe it's rather a violation of this:

> on successful PUT requests, the server will replace the entire resource addressed by the URL with the representation passed in the payload (subsequent reads will deliver the same payload)
>
> https://opensource.zalando.com/restful-api-guidelines/#put

> To respect that rule, the PUT should be made with the version property already incremented.

That would indeed *fix* it with the downside that the server shifted the burden of version increments to the clients. I wouldn't do that, but it basically is just another cons and should probably be highlighted:

> Functionality that belongs into the HTTP header becomes part of the business object

Putting the semantics of PUT aside, I believe this shows how well crafted the conditional headers are. Instead of using one header for both requests and responses there are two `ETag` and `If-Match`. For a traditional GET + PUT they both contain the same value but the semantic is different. In our example I believe it would be cleaner to use `version` as part of the response and `last_version` in the PUT request. I believe we had a section/rule about special fields that the server is free to compute upon every modification, e.g. `created_at`. Any conditional request parameters that are part of the body due to bulk constraints could be considered covered by this rule.

**Comment by tkrop** [comment]
@ddufourboivin-zalando @whiskeysierra As far as I can see the example would work the same way with version value of `2` instead of `1`. There is no effect on optimistic locking, but than it is compliant to HTTP PUT semantics. So my suggestion is to change it to `2` and to highlight this aspect for server and client side in the description.

**Comment by ddufourboivin-zalando** [comment]
# Guild meeting notes on the topic

## Notes

- Remove the … in the ETAG examples to make the example clearer (clear that the ETAG is no longer part of the object during PUT)
- For PUT with version number as part of the payload, more difficult to reach a decision.
  - The `version` property of the object should be `read-only` and not included in the `put` payload, but in a header instead
    - Which header to use?
  - Add this problem (put-is-not-what-you-get) as a CON in the Version section
  - Suggest to use POST instead of PUT since there is a server-side computation

## Next Steps

- @ddufourboivin-zalando will create a Pull Request with what he understood from the discussion.
- On that PR proposition, the guild and contributors can discuss on a more clarified field.
