### ISSUE TITLE
Document use cases and best practices for cache support.

### ISSUE THREAD

**Issue by tkrop** [zalando/restful-api-guidelines#451]
To support performance in APIs for master data resources, we should describe how to specify caching support.

**Comment by whiskeysierra** [comment]
Relevant links to this:
- Hypertext Transfer Protocol (HTTP/1.1): Caching, https://tools.ietf.org/html/rfc7234
- Storing Responses to Authenticated Requests, https://tools.ietf.org/html/rfc7234#section-3.2

I'll just use this issue as a brain dump for notes that I already had on this:
- the RFC defines the proper framework for HTTP Caching, I don't believe we need any special rules for our guidelines, maybe some examples
- the biggest aspect of this is a service/implementation aspect, rather than API design

I have three immediate ideas how caching could be implemented

1. Server-side, reverse-proxy
   - requests are passing through e.g. an nginx before the reach the actual service
   - either nginx ignores authorization headers when serving responses (very bad!)
   - or nginx uses the authorization header as part of the cache key (effectively creating per client/instance caches which may give a poor hit rate)
   - or nginx implements JWT token validation which should be doable using some custom scripts
   - or nginx always validates requests with the origin server doing the authorization (not 100% sure this works)
   - completely transparent for clients
   - doesn't save clients a roundtrip to the server
   - could be offered as a standalone appliance/docker image
2. Client-side, in-memory
   - requests are cached on each client instance, in memory
   - saves roundtrip
   - requires http client library with caching support, e.g. https://hc.apache.org/httpcomponents-client-ga/tutorial/html/caching.html
   - since each instance has their cache, the hit rate is not as good as it could be
3. Client-side, proxy
   - requests are cached on a proxy on the client side that is shared with all client instances
   - all requests to the service are done against the local proxy instead
   - proxy can ignore authorization header under the assumption that it can trust it local clients (to be discussed!)
   - transparent for client instances
   - saves remote roundtrip
   - could be offered as a standalone appliance/docker image
 
As I said I'm primarily using this as a brain dump. There is no claim of being complete.

**Comment by tfrauenstein** [comment]
yes, these are 3 variants for a generic http cache configuration (inside client instance (lib), client group specific server proxy, or general server proxy). Let me also mention local client instance caching of resources (not on http level). A typical example is read-only master data, e.g. article color palette, that is stored in-memory in master data specific cache and gets periodically updated via asynchronous http calls (which may/should support etags/cache-expiry hints).
