### ISSUE TITLE
Common field names propose an unusual naming convention for timestamp fields

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/restful-api-guidelines#506]
As part of Rule Must: Use common field names and semantics https://opensource.zalando.com/restful-api-guidelines/#174 we specify the fields `created` and `modified` to be used for audit-like timestamps.

The problem that arises is that it implicitly sets a precedent on how we should name other timestamp fields and without a `_at` suffix that makes most examples that I observe rather obscure. Examples: shipped, returned, closed, deleted, ...
They all appear to express a boolean-like condition or a status, rather than a timestamp.

Right now I see 3 options all of which have individual down sides:

1. Don't use the `at` suffix anywhere
   - consistency across fields :heavy_check_mark: 
   - in line with guidelines :heavy_check_mark: 
   - timestamp fields sound like booleans :x: 

2. Use the `at` suffix everywhere
   - consistency across fields :heavy_check_mark: 
   - in violation with guidelines :x: 
   - timestamp fields sound like timestamps :heavy_check_mark: 

3. Use `at` suffix everywhere *except* for `created` and `modified`
   - inconsistency across fields :x: 
   - in line with guidelines :heavy_check_mark: 
   - (most) timestamp fields sound like timestamps :heavy_plus_sign:

Option 3 seems to violate one of the fundamental principles of our guidelines due to the inconsistency:

> Ideally, all Zalando APIs will look like the same author created them.
>
> https://opensource.zalando.com/restful-api-guidelines/#introduction

Between option 1 and 2 I'd go with option 2 which in turn requires a (breaking) guideline change.

**Comment by dehora** [comment]
> I'd go with option 2 

:+1: for option 2—based on the reasoning it scales to name any time field. It will be a breaking change, but it's stylistic rather than technical.

**Comment by tfrauenstein** [comment]
👍 option 2

**Comment by tkrop** [comment]
I must admit, that I think using `boolean`s is an anti-pattern for APIs -- in resources as well as in parameters. As a consequence, argument three does not count for me that much. As OpenAPI supports suitable type declarations, I would favor **option 1** because it is shorter, compatible with the guidelines and will not break developer experience.

However, I'm not religious. Adding `_at` is not that much effort and may really feel a bit more precise. Therefore, I can support **option 2** too. Anyhow, adapting to the new rule and change a model will be not that easy: as I remember we state, that services should not change upstream models when they propagate them downstream. This creates a bit of a name lock in here, making us a long time live with additional inconsistencies between models.

**Option 3** is clearly is an absolute no go.

**Comment by whiskeysierra** [comment]
> I must admit, that I think using `boolean`s is an anti-pattern for APIs -- in resources as well as in parameters. As a consequence, argument three does not count for me that much.

Would you model them as statuses or absence/presence of other fields?

**Comment by tkrop** [comment]
> Would you model them as statuses or absence/presence of other fields?

I would prefer to use `x-extensible-enum`s to represent them. I'm not sure that I would always describe them as state/us properties, because this is a term I only would use in process resources.
