### ISSUE TITLE
Add section about GraphQL

### ISSUE THREAD

**Issue by tkrop** [zalando/restful-api-guidelines#514]
Review Feedback on Guideline Improvements: I always wonder how the API Guidelines are applicable to GraphQL APIs. Do we need special Guidelines for that?

**Comment by zeitlinger** [comment]
I think there would be value.

1. There are different ways to do the same thing in GraphQL - just like in REST
2. The tradeoffs are not immediately clear
3. You only find out much later what the drawbacks actually are

**Comment by tfrauenstein** [comment]
We can create Guidelines for GraphQL. And we should start based on REST Guidelines and what we currently have defined in Interface Framework, our currently major GraphQL use case. 
However, I have the feeling that it is not a worthwhile investment, since as Zalando group we currently see GraphQL as a special purpose tech with restricted usage, and not as a substitute of RESTful APIs being a widely used, general purpose service communication interface. 
And efforts significantly raise, if people then also expect GraphQL support for API Portal and API Linter. 

P.S: example citation of our https://techradar.zalando.net/languages/graphql.html: "GraphQL is not intended to generally replace standard HTTP/REST microservice communication. But it provides value for specific target domain problems, especially backends for frontends (BFF) and mobile clients."

**Comment by meshcalero** [comment]
I still believe that enabling graphql as filter-language (e.g. like the cool prototype that gregor has once built) could be a powerful and valuable extension to our REST guidelines independent from promoting graphql as replacement/alternative to REST API and by that would avoid many graphql based client gateways infront of REST API.

**Comment by ePaul** [comment]
@tfrauenstein will open a PR.

**Comment by tfrauenstein** [comment]
as discussed in API Guild: we will add to Guideline a hint about our GraphQL non/usage. And yes, GraphQL elements can be used in REST APIs for instance for filtering -- in fact it is already mentioned in https://opensource.zalando.com/restful-api-guidelines/#157 and https://opensource.zalando.com/restful-api-guidelines/#237
