### ISSUE TITLE
Filter list by age field - how to

### ISSUE THREAD

**Issue by morten-nielsen** [zalando/restful-api-guidelines#515]
You guide does not seem to describe a quite common usecase of filtering a list, e.g.
having a simple dataset of Pets, how would you get dogs younger than 5.
```json
{
 "age": 5,
 "_id": "5d2c87038b849c37dc9e3a5a",
 "name": "Coco",
 "animal": "dog",
}
```

**Comment by whiskeysierra** [comment]
It's true, there is no rule for this. We generally don't advocate for rich, powerful query languages, so nothing like `GET /pets?q=age%3C5` (`age < 5`) since only very few APIs need that (e.g. search) and they are better off defining their own query language (preferably using a structural dialect in JSON).

For most APIs that we see you wouldn't support filtering on any property using arbitrary conditions but rather on a selected few for each you'd define a dedicated query parameter, incl. a specification how they behave when combined.

Naming options from the top of my head:
- `GET /pets?max_age=5` (inclusive vs exclusive needs to be specified in the API)
- `GET /pets?younger_than=5`
- `GET /pets?birthday_before=2014-07-16` (implies that a pet has a `birthday` rather than an `age` which would have the additional benefit of being independent of time or the notion of *now*)

**Comment by nicklasfrahm** [comment]
This sounds great. Should we submit a PR to add this as a SHOULD to the guideline?

**Comment by whiskeysierra** [comment]
I'll take this to the next API guild meeting to discuss.

**Comment by whiskeysierra** [comment]
@morten-nielsen @nicklasfrahm See #518
