### ISSUE TITLE
Resources with compound keys are different than sub-resources

### ISSUE THREAD

**Issue by tfrauenstein** [zalando/restful-api-guidelines#557]
There are use cases where resources are identified via compound-keys, e.g. `article-size-advice/{sku}/{sales-channel}`. [Rule 143](https://opensource.zalando.com/restful-api-guidelines/#143) requires that a 'artificial sub-resource' is created, like `article-size-advice/{sku}/sales_channel/{sales-channel}`. This does not feel right: There is no `article-size-advice/{sku}` as an own resource with distinct life cycle. There are a couple of APIs that are not compliant to the rule or work around the rule (like above, or string concat). I vote for being less restrictive and allow `article-size-advice/{sku}/{sales-channel}` for resources with compound keys.

**Comment by whiskeysierra** [comment]
>  [Rule 143](https://opensource.zalando.com/restful-api-guidelines/#143) requires that a 'artificial sub-resource' is created, like `article-size-advice/{sku}/sales_channel/{sales-channel}`. This does not feel right: There is no `article-size-advice/{sku}` as an own resource with distinct life cycle.

If this doesn't feel right then neither should the following proposal:

> I vote for being less restrictive and allow `article-size-advice/{sku}/{sales-channel}` for resources with compound keys.

Because a resource identifiers should be a single path segment, otherwise servers are exposing compound key structure to their clients. That's a detail that clients shouldn't be concerned with.

> or work around the rule (like above, or string concat)

String concat (or any other mean to produce a reversable, single identifier) sounds like a good idea to me. Clients can take identifiers as opaque values without the need to treat their parts individually. That should make a) clients simpler and b) free servers to evolve their compound keys more freely.

**Comment by tfrauenstein** [comment]
> Because a resource identifiers should be a single path segment, otherwise servers are exposing compound key structure to their clients. That's a detail that clients shouldn't be concerned with.

But in my sample scenario the server wants to expose compound key structure, and clients have to provide both compound elements as resource id.

**Comment by whiskeysierra** [comment]
> But in my sample scenario the server wants to expose compound key structure

What's a realistic scenario when this would be desired? We already advertise to encode `id` properties as opaque strings:

> the identity of the object. If used, IDs must be opaque strings and not numbers. IDs are unique within some documented context, are stable and don’t change for a given object once assigned, and are never recycled cross entities.
>
> https://opensource.zalando.com/restful-api-guidelines/#174

Exposing a compound key/id structure in the URL feels inconsistent and against our own principles.

**Comment by tfrauenstein** [comment]
Yes, ids should be opaque. The guidance is fine, and I don't want to address this topic.
However, we have not (yet) explicitly addressed situations where resources are identified via compound keys (or compound identifier). Sometimes compound keys make perfectly sense, e.g. `article-size-advice` is provided for each article `sku` in a `sales-channel`specific way. There are many similar examples in our current APIs. 

Now the question is, how to handle it. I see ad-hoc the following variants:

a) Encode components into id: `/article-size-advice/{id}` and define in `id` description that it is actually build via `{sku}` + `_` + `{sales-channel}`. I don't like this variant, because we cannot specify the components as OpenAPI element, and client has obligation to construct the id. It is error prone and  only partial opaque. 

b) Pass the `id` components via query params with `GET /article-size-advice&sku={sku},sales_channel={sales-channel}` or via mandatory payload attributes `sku`and `sales_channel` with PUT/POST. This feels not good and is against [Rule 143](https://opensource.zalando.com/restful-api-guidelines/#143) to use path segments for resource ids. 

c) Pass only the `sku` component via path, and use 'X-Sales-Channel': `GET /article-size-advice/{sku}` and require `X-Sales-Channel={sales-channel}` as mandatory. This is against our guidance about header usage [Rule 183](https://opensource.zalando.com/restful-api-guidelines/#183), and without explicit compound id definition.  

d) Introduce sub-resource, like `/article-size-advice/{sku}/sales_channel/{sales-channel}`, conform to [Rule 143](https://opensource.zalando.com/restful-api-guidelines/#143). This is artificial and IMO misleading -- there is no sub resource with own life cycle, there is only a main resource identified via two component ids. 

e) Handle id components as id path segments: `/article-size-advice/{sku}/{sales-channel}`. This is currently not conform to [Rule 143](https://opensource.zalando.com/restful-api-guidelines/#143). However, when we defined the rule we did not discussed compound id situation. I suggest, to relax the rule as to support compound ids in the path, because ids should be preferable in the path. 

In our API landscape we can find diverse examples for all of the variants above.

**Comment by whiskeysierra** [comment]
I believe this is hard to generalize in a single rule. The example you gave is using a article/product related resource (identified by SKU) and the ability/need to further differentiate based on sales channel. That sounds a lot like a resource that behaves differently based on other context information, e.g. user (e.g. include name in the response or calculate prices based on membership) or locale (e.g. localization). Sales channel specific behavior would be another context information that the caller should (or must) provide in order to produce the right response. In this particular case I'd go with headers because I don't see this as a prime example of a compound key. They advice is identified by SKU and further differentiated by sales channel. An example for a compound key would be an exchange rate that is identified by source currency, target currency and optionally date.

Again, deriving a general rule from this is hard.

**Comment by tkrop** [comment]
I think, I have a better example: lets use the Docker image full qualified name as the id in an API. It is best described and well known as `{repository}/{name}:{tag}`. Specifying our `container-api-scanner` API using `GET /specifications/{docker-repository}/{docker-name}:{docker-tag}` violates the rule while `GET /specifications/{full-qualified-docker-image-name-and-tag}` is okay.

However, I'm not sure about changing the rules because of this single use case, because I'm generally afraid about the misuse this change opens up.

**Comment by whiskeysierra** [comment]
Would we expect that clients need to construct those compound identifiers themselves?

**Comment by tfrauenstein** [comment]
I like Tronje's compound key example (but would not agree that the article-size-advice above is a bad example). `GET /specifications/{docker-repository}/{docker-name}:{docker-tag}` is like variant e) above, and `GET /specifications/{full-qualified-docker-image-name-and-tag}` is variant a) above. 

In the latter case, client need to construct the id based on the components and the concatenation/separator rule defined in the description. In the former case the client need to construct the path from the id components. The main difference is that we make use of OpenAPI path parameter spec feature to explicitly define the compound key structure and may reuse parameter spec in other API elements (like the payload objects), instead of providing this info outside OpenAPI via id description. 

My intention is not to provide a general rule of 'how to define / design / handle compound keys'. My intention simply is that we acknowledge the compound id use case and that we either a) relax Rule 148 as to allow compound ids being passed as path parameters, or b) give the hint that id may be a compound key with components/construction rule defined in description. As argued above, I prefer a), and do not see high risk for being misused.

**Comment by whiskeysierra** [comment]
> In the latter case, client need to construct the id based on the components and the concatenation/separator rule defined in the description. In the former case the client need to construct the path from the id components.

Why would we let clients construct ids at all? Why not expose ids as opaque strings like we already advocate?

**Comment by tfrauenstein** [comment]
Can you be also more specific what variant your prefer for handling the compound key use case? (Introducing new opaque technical key as further variant?)

**Comment by whiskeysierra** [comment]
> what variant your prefer for handling the compound key use case?

To be honest, I don't see a use case to expose (i.e. document) compound keys to clients. Whether an id is a compound or scalar is a detail that only the server should be concerned with:

*As a server* I want to retain the ability to change id structure without the need to coordinate with clients.

*As a client* I don't want to be bothered with constructing complex identifiers in order to use an API. I'd rather use simple, opaque string values.

A typical usage of a REST API as I see it:
- `POST /resources`, returns `{"id":"..."}`
- `GET /resources/{id}`
- `DELETE /resource/{id}`

As a client I would just use the id and pass it back. No knowledge about its internal structure needed at all. As a server I wouldn't even document the structure, because nobody on the outside should even care. We have that problem with product ids (SKUs) already. Clients that try to parse and understand them are creating tons of problems for API providers because they can't change the internal structure without breaking anyone.

**Comment by vadeg** [comment]
Changing rule like this brings uncertanty which option should be taken by API designer. The example above 
```article-size-advice/{sku}/{sales-channel}```
 can be changed to 
```article/{sku}/size-advice/{sales-channel}``` 
or 
```article/{sku}/size-advice?sales_channel={sales-channel}```

On the other side if I have `article-size-advice/{sku}/sales_channel/{sales-channel}` then `article-size-advice/{sku}/sales_channel` should be also a valid resource. But this is not a resource. Then why is it defined? Why not `article-size-advice/{sku}?sales_channel={sales-channel}` with mandatory query param?

API's like `/path/{a}/{b}/{c}` are less extensible. Imagine that after some time is was decided that `a` should have a sub-resource `k/{k}`. Such change will break clients logic and server should now distinguish between `b` and `k/{k}` in order to process request correct. 
This also should be taken into consideration by API develpers while designing API. If there were SOLID for API I would say this is an [Open-closed principle](https://en.wikipedia.org/wiki/Open%E2%80%93closed_principle) violation :)

I think there should be a clearly defined when `/path/{a}/{b}/{c}` can be used instead of `/path/{a}/subpath/{b}/subpath/{c}` what I think is very difficult to do.
