### ISSUE TITLE
Clarify the DELETE method usage

### ISSUE THREAD

**Issue by vadeg** [zalando/restful-api-guidelines#573]
Clarify usage of `DELETE` method:
1. `DELETE` with query params should be used only for filtering in a collection and not for passing context infos that steers the behavior. For example `DELETE /orders?customer_number=12345` can delete all orders related to customer with number `12345`. Developer has to clarify the exact behaviour of such operation.

2. If `DELETE` operation requires information which can not be provided using query params then `POST /resource/{resource-id}` with body can be used (`DELETE` with body).

**Comment by vadeg** [comment]
I have a question regarding `DELETE` with query parameters. What should be the response code in this case? I see that are multiple options available depending on the use case and implementation details.

For example, server may return `200` with some content about deleted resources. It may happen that not all resources were deleted because of some reasons (errors, business logic, etc). For the client it would be nice to receive additional information what happened. If this the case then the response is almost similar to `207` response. Should we say then that returning `200` is not allowed?
Server may return `204` without content. Is it allowed to return `204` with such delete requests?
Should server return `404` if no resources found to be deleted?

**Comment by tfrauenstein** [comment]
Basically, I agree with your statements. In case of deletion of multiple resource instances matching the query filter params I would vote for 207 instead of 200 -- analog as we have defined it for batch POST; see https://opensource.zalando.com/restful-api-guidelines/#152 (perhaps extending this rule makes sense). 

I'm not 100% sure, whether we should give guidance here?
Delete with query params is a quite exotic use case, I have not yet seen at Zalando.

However, I think it is worth to give guidance on the query params -- which can be passed with all HTTP methods. They should be used as input params for (attribute) filtering in a resource collection and not for passing context infos that steers the method behavior. The latter should be passed via the payload or specific operation resources.

**Comment by mdedetrich** [comment]
@tfrauenstein We actually had this use case, although for some reason we got recommended to use `DELETE` with query params rather than using a `POST` with body, see discussion at https://chat.google.com/room/AAAAAqZDJ28/Ncp4ZPONtbA (actually you were involved in that discussion).
