### ISSUE TITLE
Robustness: clients should not break/crash when the server returns a non problem/json answer

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#624]
Rule [#176](https://opensource.zalando.com/restful-api-guidelines/#176) directs servers to always return a problem/json response if there was an error.

Unfortunately, some clients are building on this, and just completely fail when they receive some error response with a different content (e.g. text/html), when they would log problem/json content (possibly when parsing the problem object from the response, or when trying to access parts of the parsed result for a log message).

Non-problem/json responses can always occur (e.g. because of some infrastructure components like the AWS load balancer returning a 502 error when the service is not reachable, and those infrastructure components often know nothing about the API guidelines).

Clients should be prepared to handle errors without a problem/json response body gracefully, relying just on the HTTP status code for error handling. (If it's just about logging, either omit this part of the log, or log e.g. the first line of the response (if it's a text/* one).)

We could either add a sentence/paragraph to Rule 176, or add a new rule for the expected client behavior.

(Thanks to @hjacobs for the suggestion.)

**Comment by tfrauenstein** [comment]
I agree that clients should be robust against problem/json payload not being provided with 4xx and 5xx. 
There are two reasons for this.
- Provider does follow #176 but there are infrastructure components that do not support problem/json for specific error situations (e.g. AWS load balancer returning a 502 Bad Gateway)
- Provider does not follow #176 and does not return problem/json

**Comment by tkrop** [comment]
I would not see this as a guideline change, since it should be clear, that clients need to be robust against infrastructure and servers not delivering a Problem JSON. Still the wording definitely needs to be improved.

Besides, another reason for not receiving this result may be the client not declaring `application/problem+json` in its `Accept`-Header. At least `Spring` is usually not that gallant to also respond on `application/json` with a problem response without configuration.
