### ISSUE TITLE
Changelog is out of date

### ISSUE THREAD

**Issue by aaronkorver** [zalando/restful-api-guidelines#640]
https://opensource.zalando.com/restful-api-guidelines/#appendix-changelog

I see a lot of good changes being made in the repo, the published Changelog does not reflect those.

Would be nice to either update that, or direct people to release notes published elsewhere.

**Comment by vadeg** [comment]
@aaronkorver thank you. We will fix this issue in #632

**Comment by aaronkorver** [comment]
Ack! That's what I get for not reviewing PRs before opening an issue.  Thanks!!

**Comment by ePaul** [comment]
> Ack! That's what I get for not reviewing PRs before opening an issue. Thanks!!

No worries. No one could expect to find a pull-request for a two-years-out-of-date changelog right now.

We let the changelog updating slip for a while (because it usually caused merge conflicts when done right during the initial change PR), then forgot about it until we recently noticed that it was missing.

**Comment by tkrop** [comment]
Since #632 is merged, I would say we can close this.
