### ISSUE TITLE
Error when creating issues in Zally with Github Actions

### ISSUE THREAD

**Issue by vadeg** [zalando/restful-api-guidelines#667]
When Github Action tries to create tickets in Zally it fails with an error 
```
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Issue",
      "code": "missing_field",
      "field": "title"
    }
  ],
```

See [this run](https://github.com/zalando/restful-api-guidelines/runs/2736607276?check_suite_focus=true) for example.

**Comment by tkrop** [comment]
Okay, I had a look at the problem. The root cause is, that the used [scripts/deploy-travis.sh](https://github.com/zalando/restful-api-guidelines/commit/1b53d6846ee4048f605f88172cde9597f5284e69#diff-062f54bf06ccb4d627adec6fbb06547d5ba7aa51e4e2f803ca6bec01df2029b5) has only been adapted partially. I think we only need to substitute the remaining `${TRAVIS_COMMIT}` against `${GITHUB_SHA}`.

**Comment by ePaul** [comment]
It looks like it still doesn't work. @tkrop will look into this.

**Comment by tkrop** [comment]
Seems still not be working.
