### ISSUE TITLE
Identify resources by multiple ids/keys

### ISSUE THREAD

**Issue by bigunyak** [zalando/restful-api-guidelines#691]
Hi,

I want to ask if the guidelines maintainers have any opinion on the subject of working with resources which can be identified by multiple alternative keys, as this topic doesn't seem to be covered in the guidelines.

A simple example would be `customer` objects which can be identified in numerous ways, like unique internal database id, public id or social security number (SSN), maybe a temporary SSN for immigrants waiting for a permanent SSN or passport number. In big organizations some systems are built working with one type of ids while others might only be excepting other.

How one would go about designing an API which allows all types of ids used across organization?
```
GET /customers/{customer_id}
```
Where `customer_id` can be one of different id types.

If we think about ids which combine id_type and id_value as compound ids, then we could concatenate type and value in one string with some delimiter, like `customer_id="ssn:12345"`. But this might not be enough in case we support international customers, then country would also be needed. We could have country value in query string parameters but I'm not very keen on that, because we're not really searching and filtering, it's rather a lookup of a specific resource.

I've found an interesting discussion about using ZRN (custom URI scheme) which could be a potential solution, but it looks like it never made it into the guidelines (https://github.com/zalando/restful-api-guidelines/issues/62). Was it not a good idea after all?

Could you please share some ideas on this topic, as it's not covered in the guidelines on even on the Web in general?

**Comment by ePaul** [comment]
Hi @bigunyak, thank you for your question. *(This answer is not aligned with any of the other maintainers, just my personal opinion.)*

I think the clearest would be to pick one of the identifiers (one which is guaranteed to be unique, and can be exposed to your API clients) as the one to use in the `/customers/{id}` resource (for path parameters). If clients have a requirement to use other identifiers, then I would use the collection resource with a query parameter, e.g. `GET /customers?ssn=...`, potentially with additional parameters as needed. This collection resource returns multiple results, so it's not suitable for other methods than GET – this means an additional request can be needed to first fetch the main ID, and then do any operations as needed based on the main ID.

> I've found an interesting discussion about using ZRN (custom URI scheme) which could be a potential solution, but it looks like it never made it into the guidelines (#62). Was it not a good idea after all?

Huh, that was a long time ago, I barely remember this discussion.
I'm not sure where exactly it was tried out, but don't think it got much traction in the company.
(Maybe @tkrop remembers it? The other participants of that discussion have since left the company.)

In that approach, each entity would still have only one identifier, just the source of that identifier would become a namespace which avoided clashes (and it could be possibly used to look up the source of truth for that entity).
I don't think this maps cleanly to your case where every `customer` might have multiple identifiers.

**Comment by tkrop** [comment]
@bigunyak *so it is also my uncoordinated opinion*: I agree with what @ePaul said.

> I've found an interesting discussion about using ZRN (custom URI scheme) which could be a potential solution, but it looks like it never made it into the guidelines (#62). Was it not a good idea after all?

This approach was discussed to solve the challenge of representing keys from multiple namespaces transparently passing them consistently from one API to another without being forced to restructure and remap identifiers. I think, eventually the information was mapped on the edges services instead of being passed through using a consistent pattern. Anyhow, I agree that it was not envisioned for your scenario.

I have seen a couple of services in the past that served multiple concurrently existing identifiers from different namespaces using `GET /resources/{id}` where e.g. using `{id} = ( [0-9]* | [a-z][a-z0-9]* )` - having a `key-type` would have been a big improvement. While this usually works with sufficiently coordinated namespaces, I'm definitely not a fan of mixing up different identifier namespaces in the same request parameter for a single resource because of the semantic ambiguity it provides.

I agree with @ePaul that it should be granted beyond doubt that it is unique and provided by a single identity provider. Consequently, I also suggest to use `GET /resources?key=...` as pattern.
