### ISSUE TITLE
Update note about GraphQL

### ISSUE THREAD

**Issue by 130n** [zalando/restful-api-guidelines#747]
It seems like the note about GraphQL isn't really true anymore: (Added in https://github.com/zalando/restful-api-guidelines/issues/514)

https://github.com/zalando/restful-api-guidelines/blame/main/chapters/general-guidelines.adoc#L52

This is based on the [blog posts](https://engineering.zalando.com/posts/2021/03/how-we-use-graphql-at-europes-largest-fashion-e-commerce-company.html) and changes to the mentioned TechRadar ([2022.10: GraphQL is Adopt](https://opensource.zalando.com/tech-radar/)) that I've seen.

**Comment by tfrauenstein** [comment]
Yes, REST and GraphQL are on ADOPT, the latter only supplements REST to solve specific (BFF) problems. 
The guidelines actually do not contradict here, because no ADOPT statement is made. 
However, I provided an editorial update to make it clearer -- see PR https://github.com/zalando/restful-api-guidelines/pull/748
